// backend/src/models/QuizAttempt.model.js
import mongoose from 'mongoose';

const QuizAttemptSchema = new mongoose.Schema({
    student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User', // Assuming your user model is named 'User'
        required: true,
    },
    quiz: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Quiz', // Reference to the Quiz model
        required: true,
    },
    quizTitle: {
        type: String,
        required: true,
    },
    quizSubject: {
        type: String,
        required: true,
    },
    quizTopic: {
        type: String,
        required: true,
    },
    answers: [
        {
            questionId: {
                type: String, // Corresponds to the question.id in the quiz JSON
                required: true,
            },
            selectedOptionId: {
                type: String, // Corresponds to the option.id selected by the student
                default: null, // Allow for unanswered questions
            },
            isCorrect: {
                type: Boolean,
                default: false,
            },
        },
    ],
    score: {
        type: Number,
        default: 0,
    },
    totalQuestions: {
        type: Number,
        required: true,
    },
    percentage: {
        type: Number,
        default: 0,
    },
    submittedAt: {
        type: Date,
        default: Date.now,
    },
    // This field will store the analytics generated by Gemini
    geminiAnalytics: {
        type: mongoose.Schema.Types.Mixed, // Stores a flexible JSON object
        default: {},
    },
    proctoringEvents: [
        {
            timestamp: { type: Date, default: Date.now },
            eventType: { type: String, enum: ['fullscreen_exit', 'window_blur', 'copy_paste_attempt', 'other_suspicious_activity'] },
            description: { type: String },
        },
    ],
    isSuspicious: {
        type: Boolean,
        default: false,
    },
});

const QuizAttempt = mongoose.model('QuizAttempt', QuizAttemptSchema);

export default QuizAttempt;